FROM python:3.12-slim

RUN apt-get update && apt-get install -y \
    git git-lfs \
    libgl1 libglib2.0-0 \
    postgresql-client libpq-dev \
    ffmpeg netcat-openbsd \
    && git lfs install \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://huggingface.co/Supertone/supertonic-3 /supertonic/assets
RUN pip install supertonic pydub soundfile watchdog supabase celery sqlalchemy psycopg2-binary pydantic python-multipart prometheus_client
